# docker-compose.yml

version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ghs3465??
    ports: 
      - '5432:5432'
    volumes:
      - contactbook-db:/var/lib/postgresql/data

  contactbook:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  contactbook-db: